spring.datasource.url=jdbc:postgresql://localhost:5433/lifelinq
spring.datasource.username=lifelinq
spring.datasource.password=lifelinq
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration-postgres
